on:
  workflow_call:
    inputs:
      public-value:
        required: true
        type: string
    secrets:
      secret-value:
        required: true

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Reusable step
        run: |
          echo "Public value: ${{ inputs.public-value }}"
          echo "Secret value: ${{ secrets.secret-value }}"
