name: Workflow 1

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      public-value: Hello 1
    secrets:
      secret-value: World 1

  call-reusable-nested:
    uses: ./.github/workflows/reusable/nested.yml
    with:
      public-value: Hello nested
    secrets:
      secret-value: World nested
